const menu=[{
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15,
    img: './images/buttermilk cake.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
},
{
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 15,
    img: './images/diner double.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 15,
    img: './images/godzilla milkshake.jpeg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 15,
    img: './images/country delight.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 15,
    img: './images/egg attack.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 15,
    img: './images/oreo dream.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 15,
    img: './images/bacon overflow.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly  `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 15,
    img: './images/american classic.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. `,
  },
 
];
export default menu;